### ISSUE TITLE
Error 401 UNAUTHORIZED returned on start the application

### ISSUE THREAD

**Issue by doctoryGlobal** [santegoeds/oanda#16]
Dear Sir,

thank you for your fantastique application/contribution. I just read the code available and decided to try.
So I opened an fxpratice account at oanda and created a token. Then I setted it the code as the following : 

```
    client, err := oanda.NewFxPracticeClient("61247c332cfeeb26ccd24b565748482e-5dbd73ebba0540575709a23d7c0cda75")
    if err != nil {
        panic(err)
    }

    //set client id
    client.SelectAccount(137885)
```

this produce the following request : 
`Request:  &{GET https://api-fxpractice.oanda.com/v1/instruments?accountId=137885 HTTP/1.1 1 1 map[X-Accept-Datetime-Format:[UNIX] Authorization:[Bearer 61247c332cfeeb26ccd24b565748482e-5dbd73ebba0540575709a23d7c0cda75]] <nil> 0 [] false  map[] map[] <nil> map[]   <nil> <nil>}`

so when starting Oanda return the following message : 

```
Response:  &{401 UNAUTHORIZED 401 HTTP/1.1 1 1 map[Connection:[keep-alive] Server:[openresty/1.7.0.1] Date:[Mon, 15 Aug 2016 23:25:06 GMT] Content-Type:[application/json] Content-Length:[169]] 0xc08200c800 169 [] false map[] 0xc0820a4000 0xc0820ba420}
{
    "code" : 4,
    "message" : "The access token provided does not allow this request to be made",
    "moreInfo" : "http:\/\/developer.oanda.com\/docs\/v1\/auth\/#overview"
}panic: ApiError{Code: 4, Message: The access token provided does not allow this request to be made, Moreinfo: http://developer.oanda.com/docs/v1/auth/#overview}
```

I trying to figure out how to solve using a normal Personal Strategy Traders token.
Please may you help ?
or should I register the application at oanda, in this case what should be my "_Authorized redirect URI_" ?

**THANK YOU SO MUCH**

**Comment by santegoeds** [comment]
The reason for this error might be that the example in the README was incomplete and it is necessary to select an account before instruments can be listed.

I've updated the README and also included an example program that you can use to test the library.

Build the example program by running the following from the repo
``` 
go install ./...
```

Run the example program
```
example -token <oanda-token> -account <oanda-account>
```

Hope that helps...
