### ISSUE TITLE
Your library is unaware of the recently introduced 64 bit transaction id's

### ISSUE THREAD

**Issue by kciredor** [santegoeds/oanda#4]
Meaning: int's are not sufficient to store Event.TranId anymore, resulting in failures.

http://developer.oanda.com/rest-live/64-bit-transition/

**Comment by santegoeds** [comment]
Thank you for reporting this.

You should be fine as long as you're on a 64bit OS but I'll update the code shortly so that it will also work 32bit platforms.

**Comment by kciredor** [comment]
Well I'm currently running it on OS X (el capitan) 64 bit.

Forced a 64 bit build with: GOOS=darwin GOARCH=amd64 go run *.go

I have patched oanda/events.go and replaced all TranId int's with uint64..

Still no luck :-) Could it be the json decoding or so?

**Comment by santegoeds** [comment]
I'm sure I ran the tests successfully even after the 64bit transition (but I'm on 64bit Linux).

Please feel free to share your patch as a PR but I'll take a closer some time later this week regardless.

**Comment by kciredor** [comment]
I opened a work in progress PR. So, the interesting part is that:

Event{TranId: 10124722251, AccountId: 3952343 Type: MARKET_ORDER_CREATE}

All good for that order type.

But changing your account's margin (that was what I tried to do several times):

TranId is 4294967295, resulting in ApiError{Code: 13, Message: Transaction not found, Moreinfo: http://developer.oanda.com/docs/v1/transactions}

**Comment by kciredor** [comment]
Emailed OANDA api support, because the raw message for margin type already contains a 32 bit max int value. Asked them to verify if this is actually going wrong on their side.

**Comment by santegoeds** [comment]
I don't think this issue is caused by the lack of 64-bit support.

I tried building the package using GOARCH=386 and it failed to build so you must have been using a 64-bit build already (where an `int` is already 64 bits afaik).  I want to support 32 bit architectures too so I'll fix any issues there.  Currently my WIP is on branch "support-64-bit-ids" if you're interested to take a look or contribute.

I received a similar error as yours (on a 64-bit build) so I'd be interested to hear the response from OANDA api support.

**Comment by santegoeds** [comment]
Hi @kciredor - I have merged my changes for 64 bit Id support on 32 bit architectures into master.

If you still have the same problem can you please provide an example program that I can use to debug the problem?

Thanks.

**Comment by kciredor** [comment]
Very nice @santegoeds much appreciated.

You can reproduce easily by forcing a SET_MARGIN_RATE (simply change your account margin manually and listen for the event). If you fmt.Println(msg) on events.go:544, you'll see a 32 bit int already. Fairly confident it's not your (awesome) library issue now.

I'm still waiting for OANDA support, the response I received so far besides the auto reply was "we're investigating". Will definitely keep you posted!

**Comment by santegoeds** [comment]
Hi @kciredor I just fixed a bug where SET_MARGIN_RATE events/transactions were not correctly unmarshalled.

This would have resulted in a panic if you tried to access get the `Rate()` from the event.  If this was the case then please retry.

Ps I renamed `Rate()` to `MarginRate()`.

**Comment by kciredor** [comment]
Cool! Did not call Rate() yet (got stuck with the int32 TranId issue). Still waiting for OANDA...

Meanwhile I opened a PR fixing the TradeCreateEvent call for you.

**Comment by santegoeds** [comment]
Great, just merged the PR.  Many thanks!

**Comment by kciredor** [comment]
Received response from OANDA:

"Overflown transactions will be only returned for SET_MARGIN_RATE and FUND related transactions on fxPractice only as it is set by a different system. Live fxTrade platform transactions are all intact."

Closing this issue. Thanks for your time @santegoeds !
