### ISSUE TITLE
Account Id not consistent with change.

### ISSUE THREAD

**Issue by wisebaldone** [santegoeds/oanda#9]
The account Id was recently set to uint64 in some parts of the code with the alias of Id while in the account class its int.

**Comment by wisebaldone** [comment]
https://github.com/santegoeds/oanda/commit/8319e971dcd01843895f919f885d0d73c51ddc4d#diff-d0b7f86cea13f90d3cc0cc2338da8d5fR53 

this was the change and you can see in the accoutn class its still int.

**Comment by santegoeds** [comment]
Thank you for reporting this.  I'll try to get this fixed by Monday.

**Comment by santegoeds** [comment]
Fixed by PR #10

**Comment by wisebaldone** [comment]
thanks mate :)
